#!/usr/bin/env sh

# Update post.
sudo rm _posts/*Chapter*
sudo cp ~/Documents/Post/* _posts/

# Build site.
bundle exec jekyll build

# Push to master.
git add .
currentTime=`date +%H:%M/%x`
git commit -m "$currentTime"
git push origin master

echo Update Successfully!

exit 0