#!/usr/bin/env sh

# Update post.
rm _posts/*
cp ~/Documents/Posts/* _posts/

# Build site.
#bundle exec jekyll build

# Push to master.
git add .
currentTime=`date +%H:%M/%x`
git commit -m "$currentTime"
proxychains4 git push origin master

echo Update Successfully!

exit 0
